name: APIs.io - US Federal Government
description: The APIs that define the United States Federal Government.
image: https://kinlane-productions2.s3.amazonaws.com/apis-json/apis-json-logo.jpg

url: https://us-federal-government.apis.io

node: us-federal-government

keywords:

- Federal Government
- Government

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

categories_path : /categories.html
tags_path : /tags.html

github_org: api-search
github_repo: us-federal-government

search_local: true

collections:
  apis:
    output: true
    permalink: /apis/:path/
  tags:
    output: true
    permalink: /tags/:path/   
  rules:
    output: true
    permalink: /rules/:path/  
  properties:
    output: true
    permalink: /properties/:path/           

defaults:

  - scope:
      path:         ""
      type:         apis
    values:
      layout:       apis

  - scope:
      path:         ""
      type:         tags
    values:
      layout:       tags      

  - scope:
      path:         ""
      type:         rules
    values:
      layout:       rules        

  - scope:
      path:         ""
      type:         properties
    values:
      layout:       properties         